version: "3"

services:
  odoo:
    image: odoo:12.0
    container_name: odoo12
    depends_on:
      - postgres
    environment:
      - HOST=postgres
      - USER=pguser
      - PASSWORD=ambotlang
      - PORT=5432
  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=ambotlang
      - POSTGRES_USER=pguser
      - POSTGRES_DB=postgres