version: "3"

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=ambotlang
      - POSTGRES_USER=pguser
      - POSTGRES_DB=postgres
    volumes:
      - ${POSTGRES_DATA_DIR-./data/postgres}:/var/lib/postgresql/data
  odoo:
    image: odoo:12.0
networks:
  docker-net:
    driver: bridge
