version: "3"

services:
  odoo:
    image: odoo:13
    container_name: odoo
    depends_on:
      - postgres
    environment:
      - HOST=postgres
      - USER=pguser
      - PASSWORD=ambotlang
      - PORT=5432
    ports:
      - 8069:8069/tcp
    volumes:
      - ./odoo/web-data:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=ambotlang
      - POSTGRES_USER=pguser
      - POSTGRES_DB=postgres